### ISSUE TITLE
Source location during evaluation

### ISSUE THREAD

**Issue by astanziola** [ucl-bug/helmnet#12]
Feature request

* **What is the current behavior?**
Currently, there's no way to set the source location when running `evaluate.py` (see #9 ).

* **What is the expected behavior?**
To be able to set the source location while running the evaluation script

* **Other information** 
The `get_model` method accepts `source_location` it as input. Adding the functionality should be as easy as adding a new argument to `argparse` and pass it to the `__init__` method, down to `get_model`.

**Comment by wanglinfeng1** [comment]
All the problem has been solved. Thanks!

**Comment by astanziola** [comment]
No problem @wanglinfeng1 
I'd still like to keep this open until we add this functionality in the code here. 
It may be helpful for someone else who wants to do the same.

**Comment by wanglinfeng1** [comment]
It is ture that I cannot set the source location when running evaluate.py. But it is feasible in test.py.
I can train my own data and save the running results of it successfully. More importantly, both the size of the data and the location of the source can be changed.
