### ISSUE TITLE
About the hyperparameter "source_location".

### ISSUE THREAD

**Issue by wanglinfeng1** [ucl-bug/helmnet#9]
When I want to change the location of the source, for example from (82,48) to (48,48), I just changed the parameters in base.json. Then I ran the evaluate.py. However, from the prediction results, I found that the location of the source did not change, still (82,48). I am wondering what else I need to do when I want to change the location of the source, besides changing the parameters in base.json, before I run evaluate.py? What should I do If I want to test the situation of two sources or more?

Thanks a lot for your suggestions.

**Comment by astanziola** [comment]
The `base.json` file is only affecting the training loop, not the evaluation. But I agree, the possibility of changing the source during evaluation would be a nice feature to have.

In general, if you follow the example on the [README](../blob/main/README.md) you can see how to define an arbitrary source map. This should answer your question about how to test multiple sources.

**Comment by astanziola** [comment]
I'll close this as we have a specific issue to address the source location problem in #12
